import java.util.Locale

apply(plugin = "jacoco")

configure<JacocoPluginExtension> {
    toolVersion = "0.8.11"
}

tasks.withType<Test> {
    configure<JacocoTaskExtension> {
        isIncludeNoLocationClasses = true
        excludes = listOf("jdk.internal.*")
    }
}

// Custom task to generate coverage reports for Android modules
project.afterEvaluate {
    // Dynamically target standard build variants (like debug)
    val testTaskName = "testDebugUnitTest"
    val reportTaskName = "${this.name}JacocoReport"

    tasks.register<JacocoReport>(reportTaskName) {
        dependsOn(testTaskName)

        group = "Reporting"
        description = "Generate JaCoCo coverage reports for the ${project.name} module."

        reports {
            xml.required.set(true)
            html.required.set(true)
        }

        // 1. Android & Jetpack Compose Exclusions (Boilerplate & generated code)
        val fileFilter = listOf(
            "**/R.class",
            "**/R$*.class",
            "**/BuildConfig.*",
            "**/Manifest*.*",
            "**/*Test*.*",
            "android/**/*.*",
            // Jetpack Compose specific exclusions
            "**/*Composable*.*",
            "**/*Component*.*",
            "**/*Lambda*.*",
            "**/*_Specs*.*",
            "**/*Activity*.*"
        )

        // 2. Point to the compiled Java and Kotlin classes
        val javaClasses = fileTree("${project.layout.buildDirectory.get()}/intermediates/javac/debug/classes").exclude(fileFilter)
        val kotlinClasses = fileTree("${project.layout.buildDirectory.get()}/tmp/kotlin-classes/debug").exclude(fileFilter)
        classDirectories.setFrom(files(javaClasses, kotlinClasses))

        // 3. Point to the actual source code
        sourceDirectories.setFrom(files(
            "${project.projectDir}/src/main/java",
            "${project.projectDir}/src/main/kotlin"
        ))

        // 4. Point to the execution data generated by your unit tests
        executionData.setFrom(fileTree(project.layout.buildDirectory.get()) {
            include("outputs/unit_test_code_coverage/debugUnitTest/${testTaskName}.exec")
            include("jacoco/${testTaskName}.exec")
        })
    }
}