package com.nityansh.dashboard.viewmodel

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.nityansh.domain.models.CategoryItem
import com.nityansh.domain.usecase.CategoryOperationsUsecase
import com.nityansh.domain.usecase.TotalExpenseUseCase
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.firstOrNull
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class DashboardViewModel @Inject constructor(
    val categoryUseCase: CategoryOperationsUsecase,
    val totalExpenseUseCase: TotalExpenseUseCase
) : ViewModel() {

    //    var categoriesState by mutableStateOf(listOf<CategoryItem>())
    var categoriesState = categoryUseCase.getAllCategories()
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(2000), emptyList())
    var totalExpense by mutableStateOf(String())
    var newCategoryName by mutableStateOf(String())
    var showAddCategoryDialog by mutableStateOf(false)
    var categoryNameError by mutableStateOf(false)
    var categoryStatusError by mutableStateOf(false)
    var selectedOption by mutableStateOf("Enabled")

    fun addCategory() {
        if (newCategoryName.isBlank()) {
            categoryNameError = true
            return
        }
        if (selectedOption.isBlank()) {
            categoryStatusError = true
            return
        }
        val newCategory = CategoryItem(
            id = 0, // ID will be generated by the database
            name = newCategoryName, totalAmount = 0.0, enabled = selectedOption == "Enabled"
        )
        viewModelScope.launch(Dispatchers.Default) {
            categoryUseCase.addCategory(newCategory)
            clearCategory()
        }
        showAddCategoryDialog = false
    }

    fun clearCategory() {
        newCategoryName = ""
        categoryNameError = false
        categoryStatusError = false
    }

    fun addCategoryDialogClosed() {
        newCategoryName = ""
        categoryNameError = false
        categoryStatusError = false
        showAddCategoryDialog = false
    }

    fun loadTotalExpense() {
        viewModelScope.launch(Dispatchers.Default) {
            totalExpense = totalExpenseUseCase.getTotalAmount().firstOrNull()?.toString() ?: "0.0"
        }
    }
}