package com.nityansh.dashboard.viewmodel

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.nityansh.dashboard.intent.CategoryIntent
import com.nityansh.dashboard.state.AddCategoryState
import com.nityansh.dashboard.state.CategoryUiState
import com.nityansh.domain.models.CategoryItem
import com.nityansh.domain.usecase.CategoryOperationsUsecase
import com.nityansh.domain.usecase.TotalExpenseUseCase
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.firstOrNull
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class DashboardViewModel @Inject constructor(
    val categoryUseCase: CategoryOperationsUsecase, val totalExpenseUseCase: TotalExpenseUseCase
) : ViewModel() {

    var addCategoryState by mutableStateOf(AddCategoryState())

    var categoryUiState by mutableStateOf(CategoryUiState())

    init {
        fetchCategories()
    }

    fun fetchCategories() {
        val isLoading = true
        val isAddDialogVisible = false
        val error = ""
        val categoryFlow = categoryUseCase.getAllCategories()
            .stateIn(viewModelScope, SharingStarted.WhileSubscribed(2000), emptyList())

        categoryUiState = CategoryUiState(
            isLoading = isLoading,
            categories = categoryFlow,
            isAddDialogVisible = isAddDialogVisible,
            error = error
        )
    }

    fun setCategoryName(name: String) {
        addCategoryState = addCategoryState.copy(categoryName = name)
    }

    fun setCategoryStatus(status: String) {
        addCategoryState = addCategoryState.copy(isEnabled = status == "Enabled")
    }

    fun setCategoryNameErrorState(show: Boolean) {
        addCategoryState = addCategoryState.copy(showCategoryNameError = show)
    }

    fun setCategoryStatusErrorState(show: Boolean) {
        addCategoryState = addCategoryState.copy(showCategoryStatusError = show)
    }

    fun handlePlusButtonClick() {
        categoryUiState = categoryUiState.copy(isAddDialogVisible = true)
    }

    fun handleCancelButtonClick() {
        categoryUiState = categoryUiState.copy(isAddDialogVisible = false)

    }

    fun handleActions(uiIntent: CategoryIntent) {
        when (uiIntent) {
            is CategoryIntent.AddCategory -> {
                if (uiIntent.categoryName.isNullOrEmpty()) {
                    setCategoryNameErrorState(true)
                    return
                }
                if (uiIntent.isEnabled == null) {
                    setCategoryStatusErrorState(true)
                    return
                }
                val newCategory = CategoryItem(
                    id = 0, // ID will be generated by the database
                    name = uiIntent.categoryName,
                    totalAmount = 0.0,
                    enabled = uiIntent.isEnabled
                )
                viewModelScope.launch(Dispatchers.Default) {
                    categoryUseCase.addCategory(newCategory)
                    categoryUiState = categoryUiState.copy(isAddDialogVisible = false)
                    clearCategory()
                }
            }

            is CategoryIntent.DeleteCategory -> {

            }

            is CategoryIntent.UpdateCategory -> {

            }

            CategoryIntent.Nothing -> {

            }
        }
    }

    fun clearCategory() {
        addCategoryState = addCategoryState.copy(
            categoryName = "",
            showCategoryNameError = false,
            showCategoryStatusError = false,
            isEnabled = null
        )
    }

    fun loadTotalExpense() {
        viewModelScope.launch(Dispatchers.Default) {
            val totalExpense =
                totalExpenseUseCase.getTotalAmount().firstOrNull()?.toString() ?: "0.0"
            categoryUiState = categoryUiState.copy(totalAmount = totalExpense)
        }
    }
}